version: '3.1'

services:
  nginx:
    image: nginx
    #restart: always
    ports:
     - "80:80"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']