# Use root/root123456 as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
    ports:
      - 3306:3306
#windows 宿主机E盘data/mysql目录挂载到容器/var/lib/mysql目录
    volumes:
      - "E:\\data\\mysql:/var/lib/mysql"  
#  adminer:
#    image: adminer:latest
#    restart: always
#    ports:
#      - 8080:8080