version: '3.1'

services:
  redis:
    image: redis:5.0.7-alpine
    command: /etc/redis/redis.conf
    restart: always
    ports:
      - 6379:6379
#windows 宿主机D盘data/redis/data目录挂载到容器/data目录
    volumes:
      - "D:\\data\\redis\\redis.conf:/etc/redis/redis.conf"
      - "D:\\data\\redis\\data:/data"